# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from Util import Drink
from Util import Pump
from Util import Util
from PyQt5 import QtCore, QtGui, QtWidgets

"""
The following UI class was generated by the QT Designer. Small changes such as relative pathing to images was added after generation

If you generate from the .ui form provided the class will have bugs. I tried to name things to it made some sense. 

The general naming convention is (Thing/WidgetType)_(ID on page)_(Page ID)

For example: DrinkSlider_1_2G -> The FIRST DrinkSlider widget on the page with 2 sliders
"""


class Ui_Bart(object):
    def setupUi(self, Bart):
        
        self.drinkPage = ""
        scriptDir = os.path.dirname(__file__)
        Bart.setObjectName("Bart")
        Bart.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Bart.sizePolicy().hasHeightForWidth())
        Bart.setSizePolicy(sizePolicy)
        Bart.setAutoFillBackground(True)
        self.stackedWidget = QtWidgets.QStackedWidget(Bart)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 800, 480))
        self.stackedWidget.setStyleSheet("background-color:black")
        self.stackedWidget.setObjectName("stackedWidget")
        self.HomePage = QtWidgets.QWidget()
        self.HomePage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.HomePage.setAutoFillBackground(False)
        self.HomePage.setStyleSheet("background-color:black;")
        self.HomePage.setObjectName("HomePage")
        self.gridLayout = QtWidgets.QGridLayout(self.HomePage)
        self.gridLayout.setObjectName("gridLayout")
        self.Drink1 = QtWidgets.QToolButton(self.HomePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Drink1.sizePolicy().hasHeightForWidth())
        self.Drink1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        self.Drink1.setFont(font)
        self.Drink1.setStyleSheet("color: rgb(255, 255, 255);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(scriptDir, "Images/WhiskyAndCoke.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Drink1.setIcon(icon)
        self.Drink1.setIconSize(QtCore.QSize(125, 125))
        self.Drink1.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Drink1.setObjectName("Drink1")
        self.gridLayout.addWidget(self.Drink1, 0, 0, 1, 1)
        self.Drink2 = QtWidgets.QToolButton(self.HomePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Drink2.sizePolicy().hasHeightForWidth())
        self.Drink2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        self.Drink2.setFont(font)
        self.Drink2.setStyleSheet("color: rgb(255, 255, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(os.path.join(scriptDir, "Images/WhiskeyHighBall.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Drink2.setIcon(icon1)
        self.Drink2.setIconSize(QtCore.QSize(125, 125))
        self.Drink2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Drink2.setObjectName("Drink2")
        self.gridLayout.addWidget(self.Drink2, 0, 1, 1, 1)
        self.Drink3 = QtWidgets.QToolButton(self.HomePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Drink3.sizePolicy().hasHeightForWidth())
        self.Drink3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        self.Drink3.setFont(font)
        self.Drink3.setStyleSheet("color: rgb(255, 255, 255);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(os.path.join(scriptDir, "Images/Gin&Tonic.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Drink3.setIcon(icon2)
        self.Drink3.setIconSize(QtCore.QSize(125, 125))
        self.Drink3.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Drink3.setObjectName("Drink3")
        self.gridLayout.addWidget(self.Drink3, 0, 2, 1, 1)
        self.Drink4 = QtWidgets.QToolButton(self.HomePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Drink4.sizePolicy().hasHeightForWidth())
        self.Drink4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        self.Drink4.setFont(font)
        self.Drink4.setStyleSheet("color: rgb(255, 255, 255);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(os.path.join(scriptDir, "Images/SummerCollins.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Drink4.setIcon(icon3)
        self.Drink4.setIconSize(QtCore.QSize(125, 125))
        self.Drink4.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Drink4.setObjectName("Drink4")
        self.gridLayout.addWidget(self.Drink4, 1, 0, 1, 1)
        self.Drink5 = QtWidgets.QToolButton(self.HomePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Drink5.sizePolicy().hasHeightForWidth())
        self.Drink5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        self.Drink5.setFont(font)
        self.Drink5.setStyleSheet("color: rgb(255, 255, 255);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(os.path.join(scriptDir, "Images/Vodka&Lemonade.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Drink5.setIcon(icon4)
        self.Drink5.setIconSize(QtCore.QSize(125, 125))
        self.Drink5.setCheckable(False)
        self.Drink5.setChecked(False)
        self.Drink5.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Drink5.setObjectName("Drink5")
        self.gridLayout.addWidget(self.Drink5, 1, 1, 1, 1)
        self.Drink6 = QtWidgets.QToolButton(self.HomePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Drink6.sizePolicy().hasHeightForWidth())
        self.Drink6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setBold(True)
        font.setWeight(75)
        self.Drink6.setFont(font)
        self.Drink6.setStyleSheet("color: rgb(255, 255, 255);")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(os.path.join(scriptDir, "Images/MoscowMule.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Drink6.setIcon(icon5)
        self.Drink6.setIconSize(QtCore.QSize(125, 125))
        self.Drink6.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Drink6.setObjectName("Drink6")
        self.gridLayout.addWidget(self.Drink6, 1, 2, 1, 1)
        self.Drink7 = QtWidgets.QToolButton(self.HomePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Drink7.sizePolicy().hasHeightForWidth())
        self.Drink7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        self.Drink7.setFont(font)
        self.Drink7.setStyleSheet("color: rgb(255, 255, 255);")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(os.path.join(scriptDir, "Images/Unknown Drink.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Drink7.setIcon(icon6)
        self.Drink7.setIconSize(QtCore.QSize(125, 125))
        self.Drink7.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Drink7.setObjectName("Drink7")
        self.gridLayout.addWidget(self.Drink7, 2, 0, 1, 1)
        self.RandomDrink = QtWidgets.QToolButton(self.HomePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RandomDrink.sizePolicy().hasHeightForWidth())
        self.RandomDrink.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        self.RandomDrink.setFont(font)
        self.RandomDrink.setStyleSheet("color: rgb(255, 255, 255);")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(os.path.join(scriptDir, "Images/wheel-dice.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RandomDrink.setIcon(icon7)
        self.RandomDrink.setIconSize(QtCore.QSize(125, 125))
        self.RandomDrink.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.RandomDrink.setObjectName("RandomDrink")
        self.gridLayout.addWidget(self.RandomDrink, 2, 1, 1, 1)
        self.Settings = QtWidgets.QToolButton(self.HomePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Settings.sizePolicy().hasHeightForWidth())
        self.Settings.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        self.Settings.setFont(font)
        self.Settings.setStyleSheet("color : rgb(255, 255, 255);\n"
"background-color: black;\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(os.path.join(scriptDir, "Images/settings.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Settings.setIcon(icon8)
        self.Settings.setIconSize(QtCore.QSize(125, 125))
        self.Settings.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Settings.setObjectName("Settings")
        self.gridLayout.addWidget(self.Settings, 2, 2, 1, 1)
        self.stackedWidget.addWidget(self.HomePage)
        self.SettingsPage = QtWidgets.QWidget()
        self.SettingsPage.setObjectName("SettingsPage")
        self.BackArrow = QtWidgets.QPushButton(self.SettingsPage)
        self.BackArrow.setGeometry(QtCore.QRect(0, 0, 100, 50))
        self.BackArrow.setStyleSheet("background-color: black;\n"
"border: 2px solid;\n"
"border-color: white;\n"
"")
        self.BackArrow.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(os.path.join(scriptDir, "Images/BackArrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BackArrow.setIcon(icon9)
        self.BackArrow.setIconSize(QtCore.QSize(44, 50))
        self.BackArrow.setFlat(False)
        self.BackArrow.setObjectName("BackArrow")
        self.gridLayoutWidget = QtWidgets.QWidget(self.SettingsPage)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(70, 160, 681, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.ButtonLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.ButtonLayout.setContentsMargins(0, 0, 0, 0)
        self.ButtonLayout.setHorizontalSpacing(75)
        self.ButtonLayout.setObjectName("ButtonLayout")
        self.ChangePumpButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ChangePumpButton.sizePolicy().hasHeightForWidth())
        self.ChangePumpButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        self.ChangePumpButton.setFont(font)
        self.ChangePumpButton.setStyleSheet("background-color: black;\n"
"border: 2px solid;\n"
"border-color: white;\n"
"color: white;\n"
"")
        self.ChangePumpButton.setIconSize(QtCore.QSize(44, 50))
        self.ChangePumpButton.setFlat(False)
        self.ChangePumpButton.setObjectName("ChangePumpButton")
        self.ButtonLayout.addWidget(self.ChangePumpButton, 0, 1, 1, 1)
        self.CleaningButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CleaningButton.sizePolicy().hasHeightForWidth())
        self.CleaningButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        self.CleaningButton.setFont(font)
        self.CleaningButton.setStyleSheet("background-color: black;\n"
"border: 2px solid;\n"
"border-color: white;\n"
"color: white;\n"
"")
        self.CleaningButton.setIconSize(QtCore.QSize(44, 50))
        self.CleaningButton.setFlat(False)
        self.CleaningButton.setObjectName("CleaningButton")
        self.ButtonLayout.addWidget(self.CleaningButton, 0, 0, 1, 1)
        self.CustomDrinkButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CustomDrinkButton.sizePolicy().hasHeightForWidth())
        self.CustomDrinkButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        self.CustomDrinkButton.setFont(font)
        self.CustomDrinkButton.setStyleSheet("background-color: black;\n"
"border: 2px solid;\n"
"border-color: white;\n"
"color: white;\n"
"")
        self.CustomDrinkButton.setIconSize(QtCore.QSize(44, 50))
        self.CustomDrinkButton.setFlat(False)
        self.CustomDrinkButton.setObjectName("CustomDrinkButton")
        self.ButtonLayout.addWidget(self.CustomDrinkButton, 0, 2, 1, 1)
        self.stackedWidget.addWidget(self.SettingsPage)
        self.TwoDrinksGUI = QtWidgets.QWidget()
        self.TwoDrinksGUI.setObjectName("TwoDrinksGUI")
        self.BackArrow_2G = QtWidgets.QPushButton(self.TwoDrinksGUI)
        self.BackArrow_2G.setGeometry(QtCore.QRect(0, 0, 100, 50))
        self.BackArrow_2G.setStyleSheet("background-color: black;\n"
"border: 2px solid;\n"
"border-color: white;\n"
"")
        self.BackArrow_2G.setText("")
        self.BackArrow_2G.setIcon(icon9)
        self.BackArrow_2G.setIconSize(QtCore.QSize(44, 50))
        self.BackArrow_2G.setFlat(False)
        self.BackArrow_2G.setObjectName("BackArrow_2G")
        self.DrinkSlider_1_2G = QtWidgets.QSlider(self.TwoDrinksGUI)
        self.DrinkSlider_1_2G.setGeometry(QtCore.QRect(150, 140, 22, 160))
        self.DrinkSlider_1_2G.setMaximum(150)
        self.DrinkSlider_1_2G.setStyleSheet("QSlider::groove:vertical {\n"
"    position: absolute; /* absolutely position 4px from the left and right of the widget. setting margins on the widget should work too... */\n"
"    left: 4px; right: 4px;\n"
"    border-radius: 4px;\n"
"    border: 1px solid #bbb;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    height: 10px;\n"
"    background: #1F51FF;\n"
"    margin: 0 -4px; /* expand outside the groove */\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"    background: #bc13fe;\n"
"}\n"
"\n"
"QSlider::sub-page:vertical {\n"
"    background: white;\n"
"    opacity: 223;\n"
"}")
        self.DrinkSlider_1_2G.setOrientation(QtCore.Qt.Vertical)
        self.DrinkSlider_1_2G.setInvertedAppearance(False)
        self.DrinkSlider_1_2G.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.DrinkSlider_1_2G.setTickInterval(0)
        self.DrinkSlider_1_2G.setObjectName("DrinkSlider_1_2G")
        self.DrinkDisplay_1_2G = QtWidgets.QLCDNumber(self.TwoDrinksGUI)
        self.DrinkDisplay_1_2G.setGeometry(QtCore.QRect(60, 210, 81, 31))
        self.DrinkDisplay_1_2G.setStyleSheet("color: rgb(0, 255, 0);")
        self.DrinkDisplay_1_2G.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DrinkDisplay_1_2G.setFrameShadow(QtWidgets.QFrame.Plain)
        self.DrinkDisplay_1_2G.setProperty("intValue", 40)
        self.DrinkDisplay_1_2G.setObjectName("DrinkDisplay_1_2G")
        self.DrinkSlider_2_2G = QtWidgets.QSlider(self.TwoDrinksGUI)
        self.DrinkSlider_2_2G.setGeometry(QtCore.QRect(300, 140, 22, 160))
        self.DrinkSlider_2_2G.setMaximum(150)
        self.DrinkSlider_2_2G.setStyleSheet("QSlider::groove:vertical {\n"
"    position: absolute; /* absolutely position 4px from the left and right of the widget. setting margins on the widget should work too... */\n"
"    left: 4px; right: 4px;\n"
"    border-radius: 4px;\n"
"    border: 1px solid #bbb;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    height: 10px;\n"
"    background: #1F51FF;\n"
"    margin: 0 -4px; /* expand outside the groove */\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"    background: #bc13fe;\n"
"}\n"
"\n"
"QSlider::sub-page:vertical {\n"
"    background: white;\n"
"    opacity: 223;\n"
"}")
        self.DrinkSlider_2_2G.setOrientation(QtCore.Qt.Vertical)
        self.DrinkSlider_2_2G.setInvertedAppearance(False)
        self.DrinkSlider_2_2G.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.DrinkSlider_2_2G.setTickInterval(0)
        self.DrinkSlider_2_2G.setObjectName("DrinkSlider_2_2G")
        self.DrinkDisplay_2_2G = QtWidgets.QLCDNumber(self.TwoDrinksGUI)
        self.DrinkDisplay_2_2G.setGeometry(QtCore.QRect(210, 210, 81, 31))
        self.DrinkDisplay_2_2G.setStyleSheet("color: rgb(0, 255, 0);")
        self.DrinkDisplay_2_2G.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DrinkDisplay_2_2G.setFrameShadow(QtWidgets.QFrame.Plain)
        self.DrinkDisplay_2_2G.setProperty("intValue", 40)
        self.DrinkDisplay_2_2G.setObjectName("DrinkDisplay_2_2G")
        self.BrewButton_2G = QtWidgets.QPushButton(self.TwoDrinksGUI)
        self.BrewButton_2G.setGeometry(QtCore.QRect(660, 370, 111, 81))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        self.BrewButton_2G.setFont(font)
        self.BrewButton_2G.setStyleSheet("background-color: black;\n"
"border: 2px solid;\n"
"border-color: white;\n"
"color: white;")
        self.BrewButton_2G.setObjectName("BrewButton_2G")
        self.stackedWidget.addWidget(self.TwoDrinksGUI)
        self.ThreeDrinkGUI = QtWidgets.QWidget()
        self.ThreeDrinkGUI.setObjectName("ThreeDrinkGUI")
        self.DrinkSlider_2_3G = QtWidgets.QSlider(self.ThreeDrinkGUI)
        self.DrinkSlider_2_3G.setGeometry(QtCore.QRect(300, 140, 22, 160))
        self.DrinkSlider_2_3G.setStyleSheet("QSlider::groove:vertical {\n"
"    position: absolute; /* absolutely position 4px from the left and right of the widget. setting margins on the widget should work too... */\n"
"    left: 4px; right: 4px;\n"
"    border-radius: 4px;\n"
"    border: 1px solid #bbb;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    height: 10px;\n"
"    background: #1F51FF;\n"
"    margin: 0 -4px; /* expand outside the groove */\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"    background: #bc13fe;\n"
"}\n"
"\n"
"QSlider::sub-page:vertical {\n"
"    background: white;\n"
"    opacity: 223;\n"
"}")
        self.DrinkSlider_2_3G.setOrientation(QtCore.Qt.Vertical)
        self.DrinkSlider_2_3G.setInvertedAppearance(False)
        self.DrinkSlider_2_3G.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.DrinkSlider_2_3G.setTickInterval(0)
        self.DrinkSlider_2_3G.setMaximum(150)
        self.DrinkSlider_2_3G.setObjectName("DrinkSlider_2_3G")
        self.DrinkDisplay_1_3G = QtWidgets.QLCDNumber(self.ThreeDrinkGUI)
        self.DrinkDisplay_1_3G.setGeometry(QtCore.QRect(60, 210, 81, 31))
        self.DrinkDisplay_1_3G.setStyleSheet("color: rgb(0, 255, 0);")
        self.DrinkDisplay_1_3G.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DrinkDisplay_1_3G.setFrameShadow(QtWidgets.QFrame.Plain)
        self.DrinkDisplay_1_3G.setProperty("intValue", 40)
        self.DrinkDisplay_1_3G.setObjectName("DrinkDisplay_1_3G")
        self.BackArrow_3G = QtWidgets.QPushButton(self.ThreeDrinkGUI)
        self.BackArrow_3G.setGeometry(QtCore.QRect(0, 0, 100, 50))
        self.BackArrow_3G.setStyleSheet("background-color: black;\n"
"border: 2px solid;\n"
"border-color: white;\n"
"")
        self.BackArrow_3G.setText("")
        self.BackArrow_3G.setIcon(icon9)
        self.BackArrow_3G.setIconSize(QtCore.QSize(44, 50))
        self.BackArrow_3G.setFlat(False)
        self.BackArrow_3G.setObjectName("BackArrow_3G")
        self.DrinkSlider_1_3G = QtWidgets.QSlider(self.ThreeDrinkGUI)
        self.DrinkSlider_1_3G.setGeometry(QtCore.QRect(150, 140, 22, 160))
        self.DrinkSlider_1_3G.setStyleSheet("QSlider::groove:vertical {\n"
"    position: absolute; /* absolutely position 4px from the left and right of the widget. setting margins on the widget should work too... */\n"
"    left: 4px; right: 4px;\n"
"    border-radius: 4px;\n"
"    border: 1px solid #bbb;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    height: 10px;\n"
"    background: #1F51FF;\n"
"    margin: 0 -4px; /* expand outside the groove */\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"    background: #bc13fe;\n"
"}\n"
"\n"
"QSlider::sub-page:vertical {\n"
"    background: white;\n"
"    opacity: 223;\n"
"}")
        self.DrinkSlider_1_3G.setOrientation(QtCore.Qt.Vertical)
        self.DrinkSlider_1_3G.setInvertedAppearance(False)
        self.DrinkSlider_1_3G.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.DrinkSlider_1_3G.setTickInterval(0)
        self.DrinkSlider_1_3G.setMaximum(150)
        self.DrinkSlider_1_3G.setObjectName("DrinkSlider_1_3G")
        self.DrinkDisplay_2_3G = QtWidgets.QLCDNumber(self.ThreeDrinkGUI)
        self.DrinkDisplay_2_3G.setGeometry(QtCore.QRect(210, 210, 81, 31))
        self.DrinkDisplay_2_3G.setStyleSheet("color: rgb(0, 255, 0);")
        self.DrinkDisplay_2_3G.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DrinkDisplay_2_3G.setFrameShadow(QtWidgets.QFrame.Plain)
        self.DrinkDisplay_2_3G.setProperty("intValue", 40)
        self.DrinkDisplay_2_3G.setObjectName("DrinkDisplay_2_3G")
        self.DrinkSlider_3_3G = QtWidgets.QSlider(self.ThreeDrinkGUI)
        self.DrinkSlider_3_3G.setGeometry(QtCore.QRect(450, 140, 22, 160))
        self.DrinkSlider_3_3G.setStyleSheet("QSlider::groove:vertical {\n"
"    position: absolute; /* absolutely position 4px from the left and right of the widget. setting margins on the widget should work too... */\n"
"    left: 4px; right: 4px;\n"
"    border-radius: 4px;\n"
"    border: 1px solid #bbb;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    height: 10px;\n"
"    background: #1F51FF;\n"
"    margin: 0 -4px; /* expand outside the groove */\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"    background: #bc13fe;\n"
"}\n"
"\n"
"QSlider::sub-page:vertical {\n"
"    background: white;\n"
"    opacity: 223;\n"
"}")
        self.DrinkSlider_3_3G.setOrientation(QtCore.Qt.Vertical)
        self.DrinkSlider_3_3G.setInvertedAppearance(False)
        self.DrinkSlider_3_3G.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.DrinkSlider_3_3G.setTickInterval(0)
        self.DrinkSlider_3_3G.setMaximum(150)
        self.DrinkSlider_3_3G.setObjectName("DrinkSlider_3_3G")
        self.DrinkDisplay_3_3G = QtWidgets.QLCDNumber(self.ThreeDrinkGUI)
        self.DrinkDisplay_3_3G.setGeometry(QtCore.QRect(360, 210, 81, 31))
        self.DrinkDisplay_3_3G.setStyleSheet("color: rgb(0, 255, 0);")
        self.DrinkDisplay_3_3G.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DrinkDisplay_3_3G.setFrameShadow(QtWidgets.QFrame.Plain)
        self.DrinkDisplay_3_3G.setProperty("intValue", 40)
        self.DrinkDisplay_3_3G.setObjectName("DrinkDisplay_3_3G")
        self.BrewButton_3G = QtWidgets.QPushButton(self.ThreeDrinkGUI)
        self.BrewButton_3G.setGeometry(QtCore.QRect(660, 370, 111, 81))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        self.BrewButton_3G.setFont(font)
        self.BrewButton_3G.setStyleSheet("background-color: black;\n"
"border: 2px solid;\n"
"border-color: white;\n"
"color: white;")
        self.BrewButton_3G.setObjectName("BrewButton_3G")
        self.stackedWidget.addWidget(self.ThreeDrinkGUI)
        self.FourDrinkGUI = QtWidgets.QWidget()
        self.FourDrinkGUI.setObjectName("FourDrinkGUI")
        self.DrinkDisplay_2_4G = QtWidgets.QLCDNumber(self.FourDrinkGUI)
        self.DrinkDisplay_2_4G.setGeometry(QtCore.QRect(210, 210, 81, 31))
        self.DrinkDisplay_2_4G.setStyleSheet("color: rgb(0, 255, 0);")
        self.DrinkDisplay_2_4G.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DrinkDisplay_2_4G.setFrameShadow(QtWidgets.QFrame.Plain)
        self.DrinkDisplay_2_4G.setProperty("intValue", 40)
        self.DrinkDisplay_2_4G.setObjectName("DrinkDisplay_2_4G")
        self.BrewButton_4G = QtWidgets.QPushButton(self.FourDrinkGUI)
        self.BrewButton_4G.setGeometry(QtCore.QRect(660, 370, 111, 81))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        self.BrewButton_4G.setFont(font)
        self.BrewButton_4G.setStyleSheet("background-color: black;\n"
"border: 2px solid;\n"
"border-color: white;\n"
"color: white;")
        self.BrewButton_4G.setObjectName("BrewButton_4G")
        self.DrinkSlider_2_4G = QtWidgets.QSlider(self.FourDrinkGUI)
        self.DrinkSlider_2_4G.setGeometry(QtCore.QRect(300, 140, 22, 160))
        self.DrinkSlider_2_4G.setStyleSheet("QSlider::groove:vertical {\n"
"    position: absolute; /* absolutely position 4px from the left and right of the widget. setting margins on the widget should work too... */\n"
"    left: 4px; right: 4px;\n"
"    border-radius: 4px;\n"
"    border: 1px solid #bbb;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    height: 10px;\n"
"    background: #1F51FF;\n"
"    margin: 0 -4px; /* expand outside the groove */\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"    background: #bc13fe;\n"
"}\n"
"\n"
"QSlider::sub-page:vertical {\n"
"    background: white;\n"
"    opacity: 223;\n"
"}")
        self.DrinkSlider_2_4G.setOrientation(QtCore.Qt.Vertical)
        self.DrinkSlider_2_4G.setInvertedAppearance(False)
        self.DrinkSlider_2_4G.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.DrinkSlider_2_4G.setTickInterval(0)
        self.DrinkSlider_2_4G.setMaximum(150)
        self.DrinkSlider_2_4G.setObjectName("DrinkSlider_2_4G")
        self.BackArrow_4G = QtWidgets.QPushButton(self.FourDrinkGUI)
        self.BackArrow_4G.setGeometry(QtCore.QRect(0, 0, 100, 50))
        self.BackArrow_4G.setStyleSheet("background-color: black;\n"
"border: 2px solid;\n"
"border-color: white;\n"
"")
        self.BackArrow_4G.setText("")
        self.BackArrow_4G.setIcon(icon9)
        self.BackArrow_4G.setIconSize(QtCore.QSize(44, 50))
        self.BackArrow_4G.setFlat(False)
        self.BackArrow_4G.setObjectName("BackArrow_4G")
        self.DrinkDisplay_1_4G = QtWidgets.QLCDNumber(self.FourDrinkGUI)
        self.DrinkDisplay_1_4G.setGeometry(QtCore.QRect(60, 210, 81, 31))
        self.DrinkDisplay_1_4G.setStyleSheet("color: rgb(0, 255, 0);")
        self.DrinkDisplay_1_4G.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DrinkDisplay_1_4G.setFrameShadow(QtWidgets.QFrame.Plain)
        self.DrinkDisplay_1_4G.setProperty("intValue", 40)
        self.DrinkDisplay_1_4G.setObjectName("DrinkDisplay_1_4G")
        self.DrinkDisplay_3_4G = QtWidgets.QLCDNumber(self.FourDrinkGUI)
        self.DrinkDisplay_3_4G.setGeometry(QtCore.QRect(360, 210, 81, 31))
        self.DrinkDisplay_3_4G.setStyleSheet("color: rgb(0, 255, 0);")
        self.DrinkDisplay_3_4G.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DrinkDisplay_3_4G.setFrameShadow(QtWidgets.QFrame.Plain)
        self.DrinkDisplay_3_4G.setProperty("intValue", 40)
        self.DrinkDisplay_3_4G.setObjectName("DrinkDisplay_3_4G")
        self.DrinkSlider_1_4G = QtWidgets.QSlider(self.FourDrinkGUI)
        self.DrinkSlider_1_4G.setGeometry(QtCore.QRect(150, 140, 22, 160))
        self.DrinkSlider_1_4G.setStyleSheet("QSlider::groove:vertical {\n"
"    position: absolute; /* absolutely position 4px from the left and right of the widget. setting margins on the widget should work too... */\n"
"    left: 4px; right: 4px;\n"
"    border-radius: 4px;\n"
"    border: 1px solid #bbb;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    height: 10px;\n"
"    background: #1F51FF;\n"
"    margin: 0 -4px; /* expand outside the groove */\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"    background: #bc13fe;\n"
"}\n"
"\n"
"QSlider::sub-page:vertical {\n"
"    background: white;\n"
"    opacity: 223;\n"
"}")
        self.DrinkSlider_1_4G.setOrientation(QtCore.Qt.Vertical)
        self.DrinkSlider_1_4G.setInvertedAppearance(False)
        self.DrinkSlider_1_4G.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.DrinkSlider_1_4G.setTickInterval(0)
        self.DrinkSlider_1_4G.setMaximum(150)
        self.DrinkSlider_1_4G.setObjectName("DrinkSlider_1_4G")
        self.DrinkSlider_3_4G = QtWidgets.QSlider(self.FourDrinkGUI)
        self.DrinkSlider_3_4G.setGeometry(QtCore.QRect(450, 140, 22, 160))
        self.DrinkSlider_3_4G.setStyleSheet("QSlider::groove:vertical {\n"
"    position: absolute; /* absolutely position 4px from the left and right of the widget. setting margins on the widget should work too... */\n"
"    left: 4px; right: 4px;\n"
"    border-radius: 4px;\n"
"    border: 1px solid #bbb;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    height: 10px;\n"
"    background: #1F51FF;\n"
"    margin: 0 -4px; /* expand outside the groove */\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"    background: #bc13fe;\n"
"}\n"
"\n"
"QSlider::sub-page:vertical {\n"
"    background: white;\n"
"    opacity: 223;\n"
"}")
        self.DrinkSlider_3_4G.setOrientation(QtCore.Qt.Vertical)
        self.DrinkSlider_3_4G.setInvertedAppearance(False)
        self.DrinkSlider_3_4G.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.DrinkSlider_3_4G.setTickInterval(0)
        self.DrinkSlider_3_4G.setMaximum(150)
        self.DrinkSlider_3_4G.setObjectName("DrinkSlider_3_4G")
        self.DrinkDisplay_4_4G = QtWidgets.QLCDNumber(self.FourDrinkGUI)
        self.DrinkDisplay_4_4G.setGeometry(QtCore.QRect(510, 210, 81, 31))
        self.DrinkDisplay_4_4G.setStyleSheet("color: rgb(0, 255, 0);")
        self.DrinkDisplay_4_4G.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DrinkDisplay_4_4G.setFrameShadow(QtWidgets.QFrame.Plain)
        self.DrinkDisplay_4_4G.setProperty("intValue", 40)
        self.DrinkDisplay_4_4G.setObjectName("DrinkDisplay_4_4G")
        self.DrinkSlider_4_4G = QtWidgets.QSlider(self.FourDrinkGUI)
        self.DrinkSlider_4_4G.setGeometry(QtCore.QRect(600, 140, 22, 160))
        self.DrinkSlider_4_4G.setStyleSheet("QSlider::groove:vertical {\n"
"    position: absolute; /* absolutely position 4px from the left and right of the widget. setting margins on the widget should work too... */\n"
"    left: 4px; right: 4px;\n"
"    border-radius: 4px;\n"
"    border: 1px solid #bbb;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    height: 10px;\n"
"    background: #1F51FF;\n"
"    margin: 0 -4px; /* expand outside the groove */\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"    background: #bc13fe;\n"
"}\n"
"\n"
"QSlider::sub-page:vertical {\n"
"    background: white;\n"
"    opacity: 223;\n"
"}")
        self.DrinkSlider_4_4G.setOrientation(QtCore.Qt.Vertical)
        self.DrinkSlider_4_4G.setInvertedAppearance(False)
        self.DrinkSlider_4_4G.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.DrinkSlider_4_4G.setTickInterval(0)
        self.DrinkSlider_4_4G.setMaximum(150)
        self.DrinkSlider_4_4G.setObjectName("DrinkSlider_4_4G")
        self.stackedWidget.addWidget(self.FourDrinkGUI)

        self.retranslateUi(Bart)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Bart)

    def retranslateUi(self, Bart):
        _translate = QtCore.QCoreApplication.translate
        Bart.setWindowTitle(_translate("Bart", "Bart"))
        self.Drink1.setText(_translate("Bart", "Whiskey && Coke"))
        self.Drink2.setText(_translate("Bart", "High Ball"))
        self.Drink3.setText(_translate("Bart", "Gin && Tonic"))
        self.Drink4.setText(_translate("Bart", "Summer Collins"))
        self.Drink5.setText(_translate("Bart", "All-American Lemonade"))
        self.Drink6.setText(_translate("Bart", "Moscow Mule"))
        self.Drink7.setText(_translate("Bart", "NewDrink"))
        self.RandomDrink.setText(_translate("Bart", "Random Drink"))
        self.Settings.setText(_translate("Bart", "Settings"))
        self.ChangePumpButton.setText(_translate("Bart", "Change\n"
"Pump"))
        self.CleaningButton.setText(_translate("Bart", "Run\n"
"Cleaning"))
        self.CustomDrinkButton.setText(_translate("Bart", "Make\n"
"Your Own\n"
"Drink"))
        self.BrewButton_2G.setText(_translate("Bart", "Brew"))
        self.BrewButton_3G.setText(_translate("Bart", "Brew"))
        self.BrewButton_4G.setText(_translate("Bart", "Brew"))


    """
    This is the start of the non generated code.
        The next 3 functions set up the actions for clicked buttons 
    """
    def clickedSettings(self):
        self.stackedWidget.setCurrentIndex(1)
            
    def clickedBackArrow(self):
        self.stackedWidget.setCurrentIndex(0)

    def clickedDrinkButton(self, brewDrink):
        if brewDrink.ingredientCount == 2:
            self.stackedWidget.setCurrentIndex(2)
            self.UpdateSlider1_2(brewDrink.ingredients[0].volume)
            self.UpdateSlider2_2(brewDrink.ingredients[1].volume)
        elif brewDrink.ingredientCount == 3:
            self.stackedWidget.setCurrentIndex(3)
            self.UpdateSlider1_3(brewDrink.ingredients[0].volume)
            self.UpdateSlider2_3(brewDrink.ingredients[1].volume)
            self.UpdateSlider3_3(brewDrink.ingredients[2].volume)
        elif brewDrink.ingredientCount == 4:
            self.stackedWidget.setCurrentIndex(4)
            #TODO add slider updating for 
        else:
            print("Error not 2 - 4 ingredients")
        self.drinkPage = brewDrink.name

    """
    All update slider functions are desinged to set the inital value of the ingredient sliders
    when the page is first loading. The sliders and number read out are linked together and will call these functions

    - When the page is first loaded
    - When the slider is moved to update the number readout.

    """
    def UpdateSlider1_2(self, volume):
            self.DrinkSlider_1_2G.setValue(volume)
            self.DrinkDisplay_1_2G.display(self.DrinkSlider_1_2G.value())

    def UpdateSlider2_2(self, volume):
            self.DrinkSlider_2_2G.setValue(volume)
            self.DrinkDisplay_2_2G.display(self.DrinkSlider_2_2G.value())

    def UpdateSlider1_3(self, volume):
            self.DrinkSlider_1_3G.setValue(volume)
            self.DrinkDisplay_1_3G.display(self.DrinkSlider_1_3G.value())

    def UpdateSlider2_3(self, volume):
            self.DrinkSlider_2_3G.setValue(volume)
            self.DrinkDisplay_2_3G.display(self.DrinkSlider_2_3G.value())

    def UpdateSlider3_3(self, volume):
        self.DrinkSlider_3_3G.setValue(volume)
        self.DrinkDisplay_3_3G.display(self.DrinkSlider_3_3G.value())

    def UpdateSlider1_4(self, volume):
            self.DrinkSlider_1_4G.setValue(volume)
            self.DrinkDisplay_1_4G.display(self.DrinkSlider_1_4G.value())

    def UpdateSlider2_4(self, volume):
            self.DrinkSlider_2_4G.setValue(volume)
            self.DrinkDisplay_2_4G.display(self.DrinkSlider_2_4G.value())

    def UpdateSlider3_4(self, volume):
        self.DrinkSlider_3_4G.setValue(volume)
        self.DrinkDisplay_3_4G.display(self.DrinkSlider_3_4G.value())

    def UpdateSlider4_4(self, volume):
        self.DrinkSlider_4_4G.setValue(volume)
        self.DrinkDisplay_4_4G.display(self.DrinkSlider_4_4G.value())


    """
    Legacy Brew options. I should update this to one brew funtion. Should be an easy update, but it works so I left it.
    """

    def Brew2Ingredients(self, pumpList, drinkList):
        for drink in drinkList:
            if drink.name == self.drinkPage:
                print(drink)
                Util.Brew(drink, pumpList)


    def Brew3Ingredients(self, pumpList, drinkList):
        for drink in drinkList:
            if drink.name == self.drinkPage:
                print(drink)
                Util.Brew(drink, pumpList)

    def Brew4Ingredients(self, pumpList, drinkList):
        for drink in drinkList:
            if drink.name == self.drinkPage:
                print(drink)
                Util.Brew(drink, pumpList)
    """
    Set up funtions assign all of the buttons and slider actions when interacted with
    When connected the listed function will be called
    If you want to add arguments to the functions when connecting to them
    You need to use a lambda like I have for the brew functions
    """

    def SetUpSettingsPageEvents(self):
        self.Settings.clicked.connect(self.clickedSettings)
        self.BackArrow.clicked.connect(self.clickedBackArrow)
        #TODO Add other button events
            
    def SetUp2SliderPageEvents(self, pumpList, drinkList):
        self.BackArrow_2G.clicked.connect(self.clickedBackArrow)
        self.DrinkSlider_1_2G.valueChanged.connect(self.UpdateSlider1_2)
        self.DrinkSlider_2_2G.valueChanged.connect(self.UpdateSlider2_2)

        self.BrewButton_2G.clicked.connect(lambda : self.Brew2Ingredients( pumpList, drinkList))

    def SetUp3SliderPageEvents(self, pumpList, drinkList):
        self.BackArrow_3G.clicked.connect(self.clickedBackArrow)
        self.DrinkSlider_1_3G.valueChanged.connect(self.UpdateSlider1_3)
        self.DrinkSlider_2_3G.valueChanged.connect(self.UpdateSlider2_3)
        self.DrinkSlider_3_3G.valueChanged.connect(self.UpdateSlider3_3)

        self.BrewButton_3G.clicked.connect(lambda : self.Brew3Ingredients(pumpList, drinkList))

    def SetUp4SliderPageEvents(self, pumpList, drinkList):
        self.BackArrow_4G.clicked.connect(self.clickedBackArrow)
        self.DrinkSlider_1_4G.valueChanged.connect(self.UpdateSlider1_4)
        self.DrinkSlider_2_4G.valueChanged.connect(self.UpdateSlider2_4)
        self.DrinkSlider_3_4G.valueChanged.connect(self.UpdateSlider3_4)
        self.DrinkSlider_4_4G.valueChanged.connect(self.UpdateSlider4_4)

        self.BrewButton_4G.clicked.connect(lambda : self.Brew4Ingredients(pumpList, drinkList))

    def SetDrinkImages(self, drinkList):
        drinkCount = len(drinkList)
        scriptDir = os.path.dirname(__file__)
        noDrinkPath = os.path.join(scriptDir, "Images/NoAlcohol.png")
        if drinkCount >= 1:
            self.Drink1.setIcon(QtGui.QIcon(drinkList[0].imagePath))
        else:
            self.Drink1.setIcon(QtGui.QIcon(noDrinkPath))
        if drinkCount >= 2:
            self.Drink2.setIcon(QtGui.QIcon(drinkList[1].imagePath))
        else:
            self.Drink2.setIcon(QtGui.QIcon(noDrinkPath))
        if drinkCount >= 3:
            self.Drink3.setIcon(QtGui.QIcon(drinkList[2].imagePath))
        else:
            self.Drink3.setIcon(QtGui.QIcon(noDrinkPath))
        if drinkCount >= 4:
            self.Drink4.setIcon(QtGui.QIcon(drinkList[3].imagePath))
        else:
            self.Drink4.setIcon(QtGui.QIcon(noDrinkPath))
        if drinkCount >= 5:
            self.Drink5.setIcon(QtGui.QIcon(drinkList[4].imagePath))
        else:
            self.Drink5.setIcon(QtGui.QIcon(noDrinkPath))
        if drinkCount >= 6:
            self.Drink6.setIcon(QtGui.QIcon(drinkList[5].imagePath))
        else:
            self.Drink6.setIcon(QtGui.QIcon(noDrinkPath))

    def SetDrinkPages(self, drinkList):
        dl = len(drinkList)
        if dl >= 1:
            self.Drink1.clicked.connect(lambda: self.clickedDrinkButton(drinkList[0]))
        if dl >= 2:
            self.Drink2.clicked.connect(lambda: self.clickedDrinkButton(drinkList[1]))
        if dl >= 3:
            self.Drink3.clicked.connect(lambda: self.clickedDrinkButton(drinkList[2]))
        if dl >= 4:
            self.Drink4.clicked.connect(lambda: self.clickedDrinkButton(drinkList[3]))
        if dl >= 5:
            self.Drink5.clicked.connect(lambda: self.clickedDrinkButton(drinkList[4]))
        if dl >= 6:
            self.Drink6.clicked.connect(lambda: self.clickedDrinkButton(drinkList[5]))
        if dl >= 7:
            self.Drink7.clicked.connect(lambda: self.clickedDrinkButton(drinkList[6]))
    





